### ISSUE TITLE
246以上的新封包?

### ISSUE THREAD

**Issue by william32113** [kaokaotw/TMS246-Server#1]
請問3分鐘斷線該如何解決?

**Comment by rage123450** [comment]
UNK_REQ_1(1684), // [9A 7F 1F 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00]
    UNK_REQ_2(1677), // [01 00 00 00 00 00 00 00 01]
    
    UNK_ACK_1(1200),
    UNK_ACK_2(2372),
    
        @Handler(op = InHeader.UNK_REQ_2)
    public static void handleUNK_REQ_2(Client c, InPacket inPacket) {
        OutPacket outPacket = new OutPacket(OutHeader.UNK_ACK_2.getValue());
        outPacket.encodeInt(1);
        outPacket.encodeByte(1);

        c.write(outPacket);
    }

    @Handler(op = InHeader.UNK_REQ_1)
    public static void handleUNK_REQ_1(Client c, InPacket inPacket) {
        OutPacket outPacket = new OutPacket(OutHeader.UNK_ACK_1.getValue());
        outPacket.encodeLong(0);
        outPacket.encodeLong(0);

        c.write(outPacket);
    }

**Comment by william32113** [comment]
非常感謝請問我可以為你提交更新至TMS248嗎?

**Comment by william32113** [comment]
非常感謝!應該是我的楓鯊壞掉了導致沒辦法抓到一開始進地圖的這個封包

**Comment by rage123450** [comment]
他是進地圖之後發的

**Comment by rage123450** [comment]
> 非常感謝請問我可以為你提交更新至TMS248嗎?

可以阿 但你怎麼刪掉了 我逛信箱才看到

**Comment by william32113** [comment]
哈我看到你最新提交的留言感覺我這個問題有點失禮就刪掉了….

**Comment by william32113** [comment]
> 他是進地圖之後發的

對 我的楓鯊在進地圖的時候只會截到前面截不到後面發出的東西不知道怎麼回事

**Comment by william32113** [comment]
另外我正在找尋批量導出WZ成xml有推薦的嗎?

**Comment by rage123450** [comment]
沒诶 我找不到所以也一個一個導== 超麻煩
