### ISSUE TITLE
無法切換頻道

### ISSUE THREAD

**Issue by william32113** [kaokaotw/TMS246-Server#5]
沒接收到USER_TRANSFER_CHANNEL_REQUEST 包頭是對的 我猜是前面的封包有發錯內容(可能某些要發東西但發了0)

**Comment by rage123450** [comment]
對 我也不知道哪邊導致不會發換頻包

**Comment by duckYcy** [comment]
`public static OutPacket changeChannelEnable()
  {
      var p = new OutPacket(OutHeader.UNK246_518);
      p.encodeInt(0xB3247D3F);//static
      p.encodeShort(0x14);//type
      return p;
  }`
这个我之前在正服调试过，发现是缺这个包。每次切换地图、频道等等都要发一次。

**Comment by william32113** [comment]
他不會接收包@@所以發不了

**Comment by duckYcy** [comment]
。服务端直接发送即可

**Comment by william32113** [comment]
阿回好快@@我後來發現了

**Comment by william32113** [comment]
感謝回答!!

**Comment by william32113** [comment]
恩...剛剛試了一下還是沒辦法可能還有缺其他包

**Comment by william32113** [comment]
歐...我發錯地方哈哈
